spring:
  application:
    #应用名称 便于注册中心管理相关应用
    name: eurekaserver
server:
  port: 8088
eureka:
  client:
    #声明当前的eureka是一个服务端
    #是否向eureka注册
    register-with-eureka: false
    #是否自动检索生产者 设置为false 否则没有生产者会报错
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8088/eureka
